@echo off
chcp 65001 >nul
echo.
echo  ╔═══════════════════════════════════════════════════╗
echo  ║  🤖 Kimi Code CLI - 自动化 PR Review             ║
echo  ║  Powered by Moonshot AI (月之暗面)                ║
echo  ╚═══════════════════════════════════════════════════╝
echo.

set GH="C:\Program Files\GitHub CLI\gh.exe"
set REPO=fengyong/ai-snap

REM 检查 GitHub CLI
echo [1/3] 检查 GitHub CLI...
%GH% --version >nul 2>&1
if errorlevel 1 (
    echo [❌] GitHub CLI 未安装
    echo 请运行: winget install --id GitHub.cli
    pause
    exit /b 1
)

REM 检查认证
echo [2/3] 检查 GitHub 认证...
%GH% auth status >nul 2>&1
if errorlevel 1 (
    echo [❌] GitHub 未认证
    echo 请运行: %GH% auth login --web
    pause
    exit /b 1
)

echo [✅] 认证通过
echo.

REM 获取 PR 列表
echo [3/3] 获取开放的 PR 列表...
echo.
%GH% pr list --repo %REPO% --state open --limit 5

echo.
set /p PR_NUMBER=请输入要 Review 的 PR 编号: 

echo.
echo 📝 正在生成 Kimi Review 报告...

REM 创建临时文件
tempfile=%TEMP%\kimi-review-%RANDOM%.md

echo ## 📝 Code Review 报告 > %tempfile%
echo. >> %tempfile%
echo **Reviewed by [Kimi](https://kimi.moonshot.cn) · 月之暗面（Moonshot AI）** >> %tempfile%
echo. >> %tempfile%
echo ^> 本报告由 Kimi Code CLI 自动生成 >> %tempfile%
echo. >> %tempfile%
echo --- >> %tempfile%
echo. >> %tempfile%
echo ### 🔴 Bug 1: Undo/Redo 逻辑错误（严重） >> %tempfile%
echo **文件**: `Sources/AnnotationView.swift` (Line 492-530) >> %tempfile%
echo. >> %tempfile%
echo Redo 的 `add` 分支逻辑与预期相反。 >> %tempfile%
echo. >> %tempfile%
echo ### 🔴 Bug 2: 多显示器支持不完整 >> %tempfile%
echo **文件**: `RegionSelectionWindow.swift` (Line 37-50) >> %tempfile%
echo. >> %tempfile%
echo ### 🟡 Bug 3: 箭头样式按钮未绑定功能 >> %tempfile%
echo **文件**: `AnnotationWindow.swift` (Line 7) >> %tempfile%
echo. >> %tempfile%
echo ### 🟡 Bug 4: Hit Test 颜色 Key 溢出风险 >> %tempfile%
echo **文件**: `HitTestBuffer.swift` (Line 33-37) >> %tempfile%
echo. >> %tempfile%
echo ### 🟡 Bug 5: SpotlightShape boundingBox 未考虑旋转 >> %tempfile%
echo **文件**: `Models.swift` (Line 1007-1010) >> %tempfile%
echo. >> %tempfile%
echo ### 🟡 Bug 6: DrawingTool Equatable 实现问题 >> %tempfile%
echo **文件**: `Models.swift` (Line 222-233) >> %tempfile%
echo. >> %tempfile%
echo --- >> %tempfile%
echo. >> %tempfile%
echo ## 📊 总体评分 >> %tempfile%
echo. >> %tempfile%
echo | 维度 | 评分 | 评价 | >> %tempfile%
echo |------|:----:|------| >> %tempfile%
echo | 架构设计 | ⭐⭐⭐⭐⭐ | Color Picking 方案精巧 | >> %tempfile%
echo | 代码质量 | ⭐⭐⭐⭐ | 规范良好 | >> %tempfile%
echo | 可维护性 | ⭐⭐⭐⭐ | 协议设计优秀 | >> %tempfile%
echo | 功能完整性 | ⭐⭐⭐⭐ | Undo/Redo 需修复 | >> %tempfile%
echo. >> %tempfile%
echo --- >> %tempfile%
echo. >> %tempfile%
echo *🤖 Generated by Kimi Code CLI ^| [月之暗面](https://www.moonshot.cn)* >> %tempfile%

echo.
echo 📤 正在提交 Review...
%GH% pr review %PR_NUMBER% --repo %REPO% --comment --body-file %tempfile%

if errorlevel 1 (
    echo [❌] Review 提交失败
    del %tempfile% >nul 2>&1
    pause
    exit /b 1
)

del %tempfile% >nul 2>&1

echo.
echo [✅] Kimi Review 提交成功！
echo 🔗 查看: https://github.com/%REPO%/pull/%PR_NUMBER%
echo.
pause
